#+TITLE:Bspwm Config

bspwm is by far my favorite tiling window manager, which represents windows as the leaves of a full binary tree. With it, I can take full advantage of a keyboard-centric workflow, and keybindings are set using a bash-like syntax with sxhkd, a simple X hotkey daemon.

NOTE: /Property header argument `:shebang "#!/bin/sh"' is required to make the script executable after tangling, or else bspwm will refuse to start after login through sddm./

* bspwmrc
:PROPERTIES:
:header-args:shell: :tangle ~/.config/bspwm/bspwmrc :shebang "#!/bin/sh"
:END:

NOTE: /If you're using X (as I am), ensure you've added/ =exec bspwm= /to your/ =~/.xinitrc= /configuration file./

First, I define the colors to be used as the borders for each bspwm window. I usually stick to a dark-grey color-scheme for my border colors to avoid any unnecessary distractions when navigating my workspaces or windows.

#+begin_src shell

  color0=#3B4252
  color1=#D8DEE9

#+end_src

** Launch polybar

Right after bspwm starts, the polybar startup script is ran so it is ready to go by the time the background is set and bspwm is finished initializing. This usually takes < 1 second.

#+begin_src shell

  bash ~/.config/polybar/launch.sh &

#+end_src

** Launch startup script

Each time bspwm is started (or restarted) this startup script is run, which accomplishes a variety of background tasks that I would otherwise have to run manually in =vterm= or =alacritty=.

#+begin_src shell

  bash ~/.config/autostart/startup.sh &

#+end_src

** Make sure sxhkd is running

#+begin_src shell

  while :; do
    if pgrep -x sxhkd >/dev/null; then
      true
    else
      sxhkd &
    fi
    sleep 5
  done &

#+end_src

** Set keyboard layout and default cursor

#+begin_src shell

  setxkbmap -layout us
  xsetroot -cursor_name left_ptr

#+end_src

** Basic config

*** Setting window size and padding
#+begin_src shell

  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
  bspc config window_gap             8
  bspc config border_width           2
  bspc config top_padding            6
  bspc config right_padding          6
  bspc config left_padding           6
  bspc config bottom_padding         6
  bspc config top_monocle_padding    0
  bspc config left_monocle_padding   0
  bspc config right_monocle_padding  0
  bspc config bottom_monocle_padding 0
  bspc config split_ratio            0.50
  bspc config borderless_monocle     true
  bspc config gapless_monocle        true

#+end_src

*** Setting border colors
#+begin_src shell

  bspc config focused_border_color  "$color0"
  bspc config normal_border_color   "$color0"
  bspc config active_border_color   "$color0"
  bspc config presel_feedback_color "$color1"

#+end_src


** Application rules

#+begin_src shell

  bspc rule -a Steam desktop="^10"
  bspc rule -a Emacs state=tiled
  bspc rule -a Zathura state=tiled

#+end_src

** Setting the background

#+begin_src shell

  sleep 0.50
  nitrogen --set-auto "$HOME/.config/bg.png" &

#+end_src

** Jump to desktop 1

#+begin_src shell

  bspc desktop -f 1

#+end_src
